  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: :4317
        http:
          endpoint: :4318
  
  exporters:
    splunk_hec:
      token: MY-HEC-TOKEN
      endpoint: https://splunk:8088
      source: caster-simulator
      sourcetype: _json
      index: main
      log_data_enabled: true
      tls:
        insecure_skip_verify: true
  
    debug:
      verbosity: detailed
  
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [debug, splunk_hec]
      logs:
        receivers: [otlp]
        exporters: [debug, splunk_hec]
